-- 코드를 입력하세요
SELECT A.AUTHOR_ID
     , B.AUTHOR_NAME
     , A.CATEGORY
     , SUM(C.COUNT * A.PRICE) AS TOTAL_SALES
  FROM BOOK A
     , AUTHOR B
     , (SELECT BOOK_ID, SUM(SALES) AS COUNT 
          FROM BOOK_SALES 
         WHERE TO_CHAR(SALES_DATE,'YYYYMM') = '202201'
         GROUP BY BOOK_ID)C
 WHERE A.BOOK_ID = C.BOOK_ID
   AND A.AUTHOR_ID = B.AUTHOR_ID
 GROUP BY A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY
 ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC
   ;
   
   