-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID
FROM(SELECT A.USER_ID, A.PRODUCT_ID, COUNT(*) AS COUNT
       FROM ONLINE_SALE A
      GROUP BY A.USER_ID, A.PRODUCT_ID)
WHERE COUNT > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC
;