-- 코드를 입력하세요
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE,A.FAVORITES,A.ADDRESS
     , ROUND(B.REVIEW_SCORE,2) AS REVIEW_SCORE
  FROM REST_INFO A
     , (SELECT REST_ID, AVG(REVIEW_SCORE) AS REVIEW_SCORE 
          FROM REST_REVIEW
         GROUP BY REST_ID)B
 WHERE A.REST_ID = B.REST_ID
   AND A.ADDRESS LIKE '서울%'
 ORDER BY ROUND(B.REVIEW_SCORE,2) DESC, A.FAVORITES DESC
 ;