-- 코드를 입력하세요
SELECT DISTINCT B.CAR_ID AS CAR_ID
  FROM CAR_RENTAL_COMPANY_CAR A             /* 자동차 정보 */
     , CAR_RENTAL_COMPANY_RENTAL_HISTORY B  /* 자동차 대여 기록 */
 WHERE A.CAR_ID = B.CAR_ID
   AND A.CAR_TYPE = '세단'
   AND SUBSTR(TO_CHAR(B.START_DATE,'YYYYMMDD'),5,2) = '10'
 ORDER BY B.CAR_ID DESC
;
   
   
